kind = "web"
previewPath = "/"
title = "Portofolio Pelayanan & Penggembalaan"
version = "1.0.0"
id = "artifacts/portofolio-pelayanan"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18347

[services.development]
run = "pnpm --filter @workspace/portofolio-pelayanan run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/portofolio-pelayanan", "run", "build" ]
publicDir = "artifacts/portofolio-pelayanan/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18347"
BASE_PATH = "/"
